---
access_control:
  default_policy: deny
  rules:
    - networks:
        - 10.0.0.0/8
        - 127.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
      policy: allow

    - autonomous_systems:
        - 1234
        - 5678
      policy: deny

    - countries:
        - FR
      policy: allow

    - domains:
        - jellyfin.rocha.io
        - jellyseerr.rocha.io
        - wizarr.rocha.io
      countries:
        - BR
        - FR
      policy: allow

location_databases:
  - type: country
    ip_version: 4
    url: https://cdn.jsdelivr.net/npm/@ip-location-db/geolite2-geo-whois-asn-country/geolite2-geo-whois-asn-country-ipv4.csv
    cache_duration: 1d
    cache_location: /tmp/ip-db-country-ipv4.csv

  - type: country
    ip_version: 6
    url: https://cdn.jsdelivr.net/npm/@ip-location-db/geolite2-geo-whois-asn-country/geolite2-geo-whois-asn-country-ipv6.csv
    cache_duration: 1d
    cache_location: /tmp/ip-db-country-ipv6.csv

  - type: asn
    ip_version: 4
    url: https://cdn.jsdelivr.net/npm/@ip-location-db/asn/asn-ipv4.csv
    cache_duration: 1d
    cache_location: /tmp/ip-db-asn-ipv4.csv

  - type: asn
    ip_version: 6
    url: https://cdn.jsdelivr.net/npm/@ip-location-db/asn/asn-ipv6.csv
    cache_duration: 1d
    cache_location: /tmp/ip-db-asn-ipv6.csv
