---
access_control:
  default_policy: deny
  rules:
    - networks:
        - 10.0.0.0/8
        - 127.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/162
      policy: allow

    - country_codes:
        - FR
      policy: allow

    - domains:
        - jellyfin.rocha.io
        - jellyseerr.rocha.io
        - wizarr.rocha.io
      country_codes:
        - BR
        - FR
      policy: allow
