---
decisions:
  cache_file: /etc/geoblock/decisions.json
  retention: 1d

databases:
  ipv4:
    refresh_interval: 2d
    source_url: https://cdn.jsdelivr.net/npm/@ip-location-db/geolite2-country/geolite2-country-ipv4.csv
    cache_file: /etc/geoblock/database_ipv4.json
  ipv6:
    refresh_interval: 2d
    source_url: https://cdn.jsdelivr.net/npm/@ip-location-db/geolite2-country/geolite2-country-ipv6.csv
    cache_file: /etc/geoblock/database_ipv6.json

access_control:
  default_policy: deny
  rules:
    - networks:
        - 10.0.0.0/8
        - 127.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
      policy: allow

    - country_codes:
        - FR
      policy: allow

    - domains:
        - jellyfin.rocha.io
        - jellyseerr.rocha.io
        - wizarr.rocha.io
      country_codes:
        - BR
        - FR
      policy: allow
