# =============================================================================
# Tools (Dev Dependencies)
# =============================================================================

.PHONY: install
install: ## Install development dependencies
	go install github.com/boumenot/gocover-cobertura
	go install github.com/mgechev/revive
	go install github.com/securego/gosec/v2/cmd/gosec
	go install github.com/segmentio/golines
	go install mvdan.cc/gofumpt
