---
name: Build and test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.2'

      - name: Run tests
        run: make test
