name: Tag on release

on:
  push:
    branches: ['main']

jobs:
  tag-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Tag release
        id: commit_message
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          commit_msg=$(git log -1 --pretty=%B)
          if [[ $commit_msg =~ ^release:\ v?([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            tag="v${BASH_REMATCH[1]}"
            git tag "$tag"
            git push origin "$tag"
          fi
